"""
SentinelOps Dashboard Backend – PostgreSQL / SQLAlchemy edition.
All JSON-file persistence has been replaced with ORM operations.
Scanner report files (sast-report.json, trivy-report.json, etc.) still
live on disk because they are generated by the pipeline toolchain.
"""

from flask import Flask, jsonify, request, redirect, session
from flask_cors import CORS
from flask_jwt_extended import (
    JWTManager,
    create_access_token,
    jwt_required,
    get_jwt_identity,
    get_jwt,
)
import json
import os
import sys
import hmac
import hashlib
import re
import uuid
import secrets as _secrets
from datetime import datetime, timedelta
from typing import Dict

import bcrypt
from dotenv import load_dotenv

# ---------------------------------------------------------------------------
# Environment
# ---------------------------------------------------------------------------
load_dotenv(
    os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), ".env")
)

# ---------------------------------------------------------------------------
# Pipeline module
# ---------------------------------------------------------------------------
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from pipeline.pipeline_executor import (
    PipelineExecutor,
    run_pipeline_async,
    run_pipeline,
    run_pipeline_background,
    validate_repo_url,
    PipelineResult,
)
from pipeline.sast_scanner import LANGUAGE_INFO, TOOL_DISPLAY

# Google OAuth (optional)
try:
    from authlib.integrations.requests_client import OAuth2Session

    OAUTH_AVAILABLE = True
except ImportError:
    OAUTH_AVAILABLE = False

# ---------------------------------------------------------------------------
# Flask application
# ---------------------------------------------------------------------------
app = Flask(__name__)
app.secret_key = os.environ.get(
    "JWT_SECRET_KEY", "sentinelops-secret-key-change-in-production"
)
CORS(app, supports_credentials=True)

# ---------------------------------------------------------------------------
# Database (SQLAlchemy + Flask-Migrate)
# ---------------------------------------------------------------------------
DATABASE_URL = os.environ.get(
    "DATABASE_URL", "postgresql://sentinelops:sentinelops@localhost:5432/sentinelops"
)
app.config["SQLALCHEMY_DATABASE_URI"] = DATABASE_URL
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
app.config["SQLALCHEMY_ENGINE_OPTIONS"] = {
    "pool_size": int(os.environ.get("DB_POOL_SIZE", 10)),
    "max_overflow": int(os.environ.get("DB_MAX_OVERFLOW", 20)),
    "pool_pre_ping": True,
}

from database import db, migrate, init_db  # noqa: E402

init_db(app)

from models import (  # noqa: E402
    User,
    Config,
    Policy,
    Notification,
    Pipeline,
    ScanResult,
    Vulnerability,
    Secret,
    UserSettings,
    ApiToken,
    WebhookLog,
    SystemLog,
)

# ---------------------------------------------------------------------------
# JWT Configuration
# ---------------------------------------------------------------------------
app.config["JWT_SECRET_KEY"] = os.environ.get(
    "JWT_SECRET_KEY", "sentinelops-secret-key-change-in-production"
)
app.config["JWT_ACCESS_TOKEN_EXPIRES"] = timedelta(hours=24)
app.config["JWT_TOKEN_LOCATION"] = ["headers"]
app.config["JWT_HEADER_NAME"] = "Authorization"
app.config["JWT_HEADER_TYPE"] = "Bearer"
jwt_manager = JWTManager(app)

# ---------------------------------------------------------------------------
# Google OAuth 2.0 configuration
# ---------------------------------------------------------------------------
GOOGLE_CLIENT_ID = os.environ.get("GOOGLE_CLIENT_ID", "")
GOOGLE_CLIENT_SECRET = os.environ.get("GOOGLE_CLIENT_SECRET", "")
GOOGLE_DISCOVERY_URL = "https://accounts.google.com/.well-known/openid-configuration"
GOOGLE_AUTH_URI = "https://accounts.google.com/o/oauth2/v2/auth"
GOOGLE_TOKEN_URI = "https://oauth2.googleapis.com/token"
GOOGLE_USERINFO_URI = "https://openidconnect.googleapis.com/v1/userinfo"
GOOGLE_SCOPES = ["openid", "email", "profile"]

# ---------------------------------------------------------------------------
# JWT error handlers
# ---------------------------------------------------------------------------

@jwt_manager.invalid_token_loader
def invalid_token_callback(error_string):
    return jsonify({"error": "Invalid token", "message": error_string}), 401


@jwt_manager.unauthorized_loader
def unauthorized_callback(error_string):
    return jsonify({"error": "Missing token", "message": error_string}), 401


@jwt_manager.expired_token_loader
def expired_token_callback(jwt_header, jwt_payload):
    return jsonify({"error": "Token expired"}), 401


# ---------------------------------------------------------------------------
# Directories – only REPORT_DIR is still needed for scanner artefacts
# ---------------------------------------------------------------------------
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
REPORT_DIR = os.path.join(os.path.dirname(BASE_DIR), "runtime", "reports")
os.makedirs(REPORT_DIR, exist_ok=True)

# Pipeline executor still writes its own history JSON (independent module)
PIPELINE_DIR = os.path.join(BASE_DIR, "data", "pipelines")
os.makedirs(PIPELINE_DIR, exist_ok=True)
PIPELINES_FILE = os.path.join(PIPELINE_DIR, "history.json")
pipeline_executor = PipelineExecutor(REPORT_DIR, PIPELINES_FILE)

# GitHub webhook secret
GITHUB_WEBHOOK_SECRET = os.environ.get("GITHUB_WEBHOOK_SECRET", "your-webhook-secret")


# ====================================================================
# HELPER: load scanner report from disk (unchanged)
# ====================================================================

def load_json_file(filename):
    """Load a JSON report file from REPORT_DIR."""
    path = os.path.join(REPORT_DIR, filename)
    try:
        with open(path) as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return None


# ====================================================================
# HELPER: current user from JWT
# ====================================================================

def get_current_user_info():
    """Return basic user info extracted from the JWT claims."""
    user_id = get_jwt_identity()
    claims = get_jwt()
    return {
        "id": int(user_id),
        "username": claims.get("username"),
        "email": claims.get("email"),
        "role": claims.get("role"),
    }


def get_full_user_info(user_id):
    """Fetch full user record from the database."""
    user = db.session.get(User, user_id)
    if user:
        return {
            "id": user.id,
            "username": user.username,
            "email": user.email,
            "role": user.role,
            "fullName": user.full_name or "",
            "organization": user.organization or "",
            "roleTitle": user.role_title or "",
        }
    return None


# ====================================================================
# HELPER: notifications
# ====================================================================

def add_notification(notification_type: str, title: str, message: str, metadata: dict = None):
    """Create a new system notification and persist it in the database."""
    notif = Notification(
        id=str(uuid.uuid4())[:8],
        type=notification_type,
        title=title,
        message=message,
        read=False,
    )
    notif.extra_data = metadata or {}
    db.session.add(notif)
    db.session.commit()

    # Prune old notifications (keep last 100)
    count = Notification.query.count()
    if count > 100:
        oldest = (
            Notification.query
            .order_by(Notification.created_at.asc())
            .limit(count - 100)
            .all()
        )
        for o in oldest:
            db.session.delete(o)
        db.session.commit()

    return notif


def verify_github_signature(payload_body, signature_header):
    """Verify GitHub webhook HMAC-SHA256 signature."""
    if not signature_header:
        return False
    hash_object = hmac.new(
        GITHUB_WEBHOOK_SECRET.encode("utf-8"),
        msg=payload_body,
        digestmod=hashlib.sha256,
    )
    expected = "sha256=" + hash_object.hexdigest()
    return hmac.compare_digest(expected, signature_header)


# ====================================================================
# AUTH ROUTES
# ====================================================================

@app.route("/api/auth/login", methods=["POST"])
def login():
    """Authenticate user and return a JWT."""
    data = request.get_json()
    username = data.get("username", "").strip()
    password = data.get("password", "")

    if not username or not password:
        return jsonify({"error": "Username and password are required"}), 400

    user = User.query.filter_by(username=username).first()

    if not user:
        return jsonify({"error": "Invalid credentials"}), 401

    if user.auth_provider == "google" and not user.password_hash:
        return jsonify({"error": "This account uses Google Sign-In. Please login with Google."}), 401

    if not bcrypt.checkpw(password.encode("utf-8"), user.password_hash.encode("utf-8")):
        return jsonify({"error": "Invalid credentials"}), 401

    user.last_login_at = datetime.now()
    db.session.commit()

    access_token = create_access_token(
        identity=str(user.id),
        additional_claims={
            "username": user.username,
            "email": user.email,
            "role": user.role,
        },
    )

    return jsonify({
        "token": access_token,
        "user": {
            "id": user.id,
            "username": user.username,
            "email": user.email,
            "role": user.role,
            "fullName": user.full_name or "",
            "organization": user.organization or "",
            "roleTitle": user.role_title or "",
            "authProvider": user.auth_provider,
        },
    })


@app.route("/api/auth/me", methods=["GET"])
@jwt_required()
def get_current_user():
    """Return the authenticated user's full profile."""
    current = get_current_user_info()
    full = get_full_user_info(current["id"])
    return jsonify(full if full else current)


@app.route("/api/auth/signup", methods=["POST"])
def signup():
    """Public self-service signup – creates a *viewer* account."""
    data = request.get_json()

    username = data.get("username", "").strip()
    email = data.get("email", "").strip()
    password = data.get("password", "")
    full_name = data.get("fullName", "").strip()
    organization = data.get("organization", "").strip()
    role_title = data.get("roleTitle", "").strip()
    phone = data.get("phone", "").strip()

    # --- Validation ---
    errors = []
    if not username:
        errors.append("Username is required")
    elif len(username) < 3:
        errors.append("Username must be at least 3 characters")
    elif not re.match(r"^[a-zA-Z0-9_.-]+$", username):
        errors.append("Username can only contain letters, numbers, dots, hyphens, and underscores")
    if not email:
        errors.append("Email is required")
    elif not re.match(r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$", email):
        errors.append("Invalid email format")
    if not password:
        errors.append("Password is required")
    elif len(password) < 6:
        errors.append("Password must be at least 6 characters")
    if not full_name:
        errors.append("Full name is required")
    if errors:
        return jsonify({"error": errors[0], "errors": errors}), 400

    if User.query.filter(db.func.lower(User.username) == username.lower()).first():
        return jsonify({"error": "Username already exists"}), 409
    if User.query.filter(db.func.lower(User.email) == email.lower()).first():
        return jsonify({"error": "Email already exists"}), 409

    new_user = User(
        username=username,
        email=email,
        password_hash=bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt()).decode("utf-8"),
        role="viewer",
        full_name=full_name,
        organization=organization,
        role_title=role_title,
        phone=phone,
        auth_provider="local",
    )
    db.session.add(new_user)
    db.session.commit()

    return jsonify({
        "message": "Account created successfully! Please sign in.",
        "user": {
            "id": new_user.id,
            "username": new_user.username,
            "email": new_user.email,
            "role": new_user.role,
            "fullName": new_user.full_name,
        },
    }), 201


@app.route("/api/auth/register", methods=["POST"])
@jwt_required()
def register():
    """Admin-only user creation – any role can be assigned."""
    current_user = get_current_user_info()
    if current_user["role"] != "admin":
        return jsonify({"error": "Admin access required"}), 403

    data = request.get_json()
    username = data.get("username", "").strip()
    email = data.get("email", "").strip()
    password = data.get("password", "")
    role = data.get("role", "viewer")
    full_name = data.get("fullName", "").strip()
    organization = data.get("organization", "").strip()
    role_title = data.get("roleTitle", "").strip()
    phone = data.get("phone", "").strip()

    if not username or not email or not password:
        return jsonify({"error": "Username, email and password are required"}), 400

    valid_roles = ["admin", "user", "viewer"]
    if role not in valid_roles:
        return jsonify({"error": f"Invalid role. Must be one of: {', '.join(valid_roles)}"}), 400

    if User.query.filter(db.func.lower(User.username) == username.lower()).first():
        return jsonify({"error": "Username already exists"}), 409
    if User.query.filter(db.func.lower(User.email) == email.lower()).first():
        return jsonify({"error": "Email already exists"}), 409

    new_user = User(
        username=username,
        email=email,
        password_hash=bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt()).decode("utf-8"),
        role=role,
        full_name=full_name,
        organization=organization,
        role_title=role_title,
        phone=phone,
        auth_provider="local",
    )
    db.session.add(new_user)
    db.session.commit()

    return jsonify({
        "message": "User created successfully",
        "user": {
            "id": new_user.id,
            "username": new_user.username,
            "email": new_user.email,
            "role": new_user.role,
            "fullName": new_user.full_name,
        },
    }), 201


# ====================================================================
# GOOGLE OAUTH ROUTES
# ====================================================================

@app.route("/api/auth/google", methods=["GET"])
def google_login():
    """Redirect to Google OAuth consent screen."""
    if not OAUTH_AVAILABLE:
        return jsonify({"error": "OAuth library not installed"}), 500
    if not GOOGLE_CLIENT_ID or GOOGLE_CLIENT_ID == "your-google-client-id":
        return jsonify({"error": "Google OAuth not configured. Set GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET in .env"}), 503

    oauth_client = OAuth2Session(
        client_id=GOOGLE_CLIENT_ID,
        client_secret=GOOGLE_CLIENT_SECRET,
        redirect_uri=request.url_root.rstrip("/") + "/api/auth/google/callback",
        scope=" ".join(GOOGLE_SCOPES),
    )
    authorization_url, state = oauth_client.create_authorization_url(GOOGLE_AUTH_URI)
    session["oauth_state"] = state
    return redirect(authorization_url)


@app.route("/api/auth/google/callback", methods=["GET"])
def google_callback():
    """Handle the OAuth callback from Google."""
    if not OAUTH_AVAILABLE:
        return jsonify({"error": "OAuth library not installed"}), 500

    code = request.args.get("code")
    if not code:
        return redirect("http://localhost:3000/login?error=google_auth_failed")

    try:
        oauth_client = OAuth2Session(
            client_id=GOOGLE_CLIENT_ID,
            client_secret=GOOGLE_CLIENT_SECRET,
            redirect_uri=request.url_root.rstrip("/") + "/api/auth/google/callback",
            state=session.get("oauth_state"),
        )
        oauth_client.fetch_token(GOOGLE_TOKEN_URI, code=code)
        resp = oauth_client.get(GOOGLE_USERINFO_URI)
        google_user = resp.json()

        google_email = google_user.get("email", "")
        google_name = google_user.get("name", "")
        google_sub = google_user.get("sub", "")

        if not google_email:
            return redirect("http://localhost:3000/login?error=no_email")

        existing = User.query.filter(db.func.lower(User.email) == google_email.lower()).first()

        if existing:
            existing.last_login_at = datetime.now()
            if not existing.auth_provider:
                existing.auth_provider = "google"
            db.session.commit()
            user = existing
        else:
            # Generate unique username
            base_username = google_email.split("@")[0]
            username = base_username
            counter = 1
            while User.query.filter(db.func.lower(User.username) == username.lower()).first():
                username = f"{base_username}{counter}"
                counter += 1

            user = User(
                username=username,
                email=google_email,
                password_hash="",
                role="viewer",
                full_name=google_name,
                auth_provider="google",
                google_id=google_sub,
                last_login_at=datetime.now(),
            )
            db.session.add(user)
            db.session.commit()

        access_token = create_access_token(
            identity=str(user.id),
            additional_claims={
                "username": user.username,
                "email": user.email,
                "role": user.role,
            },
        )
        return redirect(f"http://localhost:3000/login?token={access_token}&provider=google")

    except Exception as e:
        app.logger.error(f"Google OAuth error: {e}")
        return redirect(f"http://localhost:3000/login?error=oauth_error&message={str(e)}")


@app.route("/api/auth/change-password", methods=["POST"])
@jwt_required()
def change_password():
    """Change the current user's password."""
    current = get_current_user_info()
    data = request.get_json()
    current_password = data.get("currentPassword", "")
    new_password = data.get("newPassword", "")

    if not current_password or not new_password:
        return jsonify({"error": "Both current and new password are required"}), 400

    user = db.session.get(User, current["id"])
    if not user:
        return jsonify({"error": "User not found"}), 404

    if not bcrypt.checkpw(current_password.encode("utf-8"), user.password_hash.encode("utf-8")):
        return jsonify({"error": "Current password is incorrect"}), 401

    if len(new_password) < 6:
        return jsonify({"error": "New password must be at least 6 characters"}), 400

    user.password_hash = bcrypt.hashpw(new_password.encode("utf-8"), bcrypt.gensalt()).decode("utf-8")
    db.session.commit()

    return jsonify({"message": "Password changed successfully"})


# ====================================================================
# POLICY ROUTES
# ====================================================================

@app.route("/api/policy", methods=["GET"])
@jwt_required()
def get_policy_route():
    """Return the current security policy."""
    policy = Policy.get_instance()
    return jsonify(policy.to_dict())


@app.route("/api/policy", methods=["PUT"])
@jwt_required()
def update_policy_route():
    """Update the security policy."""
    current_user = get_current_user_info()
    if current_user["role"] != "admin":
        return jsonify({"error": "Admin access required"}), 403

    data = request.get_json()
    policy = Policy.get_instance()

    if "minScore" in data:
        policy.min_score = max(0, min(100, int(data["minScore"])))
    if "blockCritical" in data:
        policy.block_critical = bool(data["blockCritical"])
    if "blockHigh" in data:
        policy.block_high = bool(data["blockHigh"])
    if "maxCriticalVulns" in data:
        policy.max_critical_vulns = max(0, int(data["maxCriticalVulns"]))
    if "maxHighVulns" in data:
        policy.max_high_vulns = max(0, int(data["maxHighVulns"]))
    if "autoBlock" in data:
        policy.auto_block = bool(data["autoBlock"])

    policy.updated_at = datetime.now()
    policy.updated_by = current_user["username"]
    db.session.commit()

    return jsonify({"message": "Policy updated successfully", "policy": policy.to_dict()})


@app.route("/api/policy/evaluate", methods=["GET"])
@jwt_required()
def evaluate_policy():
    """Evaluate the current reports against the security policy."""
    policy = Policy.get_instance()

    sast_data = load_json_file("sast-report.json")
    bandit_data = load_json_file("bandit-report.json")
    trivy_data = load_json_file("trivy-report.json")
    gitleaks_data = load_json_file("gitleaks-report.json")
    dast_data = load_json_file("dast-report.json")

    # ---- SAST score ----
    sast_score = 100
    sast_critical = 0
    sast_high = 0
    sast_medium = 0
    sast_low = 0

    if sast_data and sast_data.get("metrics"):
        totals = sast_data["metrics"].get("totals", {})
        sast_critical = totals.get("critical", 0)
        sast_high = totals.get("high", 0)
        sast_medium = totals.get("medium", 0)
        sast_low = totals.get("low", 0)
    elif bandit_data and bandit_data.get("results"):
        for r in bandit_data["results"]:
            sev = r.get("issue_severity", "").upper()
            if sev == "HIGH":
                sast_high += 1
            elif sev == "MEDIUM":
                sast_medium += 1
            else:
                sast_low += 1

    sast_score -= sast_critical * 15 + sast_high * 8 + sast_medium * 3 + sast_low * 1
    sast_score = max(0, sast_score)

    # ---- Trivy score ----
    trivy_score = 100
    trivy_critical = 0
    trivy_high = 0
    trivy_medium = 0
    trivy_low = 0

    if trivy_data and trivy_data.get("Results"):
        for result in trivy_data["Results"]:
            for vuln in result.get("Vulnerabilities", []):
                sev = vuln.get("Severity", "").upper()
                if sev == "CRITICAL":
                    trivy_critical += 1
                elif sev == "HIGH":
                    trivy_high += 1
                elif sev == "MEDIUM":
                    trivy_medium += 1
                else:
                    trivy_low += 1
    trivy_score -= trivy_critical * 15 + trivy_high * 8 + trivy_medium * 3 + trivy_low * 1
    trivy_score = max(0, trivy_score)

    # ---- Gitleaks score ----
    gitleaks_score = 100
    gitleaks_total = 0
    gitleaks_critical = 0
    gitleaks_high = 0

    if gitleaks_data:
        gitleaks_total = gitleaks_data.get("total_secrets", 0)
        gitleaks_critical = gitleaks_data.get("metrics", {}).get("critical", 0)
        gitleaks_high = gitleaks_data.get("metrics", {}).get("high", 0)
    gitleaks_score -= gitleaks_critical * 20 + gitleaks_high * 12 + (gitleaks_total - gitleaks_critical - gitleaks_high) * 5
    gitleaks_score = max(0, gitleaks_score)

    # ---- DAST score ----
    dast_score = 100
    dast_high = 0
    dast_medium = 0
    dast_low = 0

    if dast_data:
        dast_high = dast_data.get("metrics", {}).get("high", 0)
        dast_medium = dast_data.get("metrics", {}).get("medium", 0)
        dast_low = dast_data.get("metrics", {}).get("low", 0)
    dast_score -= dast_high * 10 + dast_medium * 4 + dast_low * 1
    dast_score = max(0, dast_score)

    # ---- Composite ----
    weights = {"sast": 0.35, "trivy": 0.25, "gitleaks": 0.25, "dast": 0.15}
    composite = round(
        sast_score * weights["sast"]
        + trivy_score * weights["trivy"]
        + gitleaks_score * weights["gitleaks"]
        + dast_score * weights["dast"]
    )

    total_critical = sast_critical + trivy_critical + gitleaks_critical
    total_high = sast_high + trivy_high + dast_high

    # ---- Decision ----
    is_deployable = True
    reasons = []

    if composite < policy.min_score:
        is_deployable = False
        reasons.append(f"Security score {composite} below minimum {policy.min_score}")
    if policy.block_critical and total_critical > policy.max_critical_vulns:
        is_deployable = False
        reasons.append(f"{total_critical} critical vulnerabilities (max {policy.max_critical_vulns})")
    if policy.block_high and total_high > policy.max_high_vulns:
        is_deployable = False
        reasons.append(f"{total_high} high vulnerabilities (max {policy.max_high_vulns})")

    return jsonify({
        "security_score": composite,
        "is_deployable": is_deployable,
        "reasons": reasons,
        "scores": {
            "sast": sast_score,
            "trivy": trivy_score,
            "gitleaks": gitleaks_score,
            "dast": dast_score,
        },
        "vulnerability_summary": {
            "critical": total_critical,
            "high": total_high,
            "medium": sast_medium + trivy_medium + dast_medium,
            "low": sast_low + trivy_low + dast_low,
        },
        "policy": policy.to_dict(),
        "evaluated_at": datetime.now().isoformat(),
    })


# ====================================================================
# REPORT ROUTES (still file-based – scanner artefacts)
# ====================================================================

@app.route("/api/bandit")
@jwt_required()
def bandit():
    data = load_json_file("bandit-report.json")
    if data is None:
        return jsonify({"error": "Bandit report not found"}), 404
    return jsonify(data)


@app.route("/api/sast")
@jwt_required()
def sast():
    data = load_json_file("sast-report.json")
    if data:
        return jsonify(data)
    data = load_json_file("bandit-report.json")
    if data:
        return jsonify(data)
    return jsonify({"error": "SAST report not found. Run a scan first."}), 404


@app.route("/api/sast/languages")
@jwt_required()
def sast_languages():
    return jsonify({"languages": LANGUAGE_INFO, "tools": TOOL_DISPLAY})


@app.route("/api/trivy")
@jwt_required()
def trivy():
    data = load_json_file("trivy-report.json")
    if data is None:
        return jsonify({"error": "Trivy report not found"}), 404
    return jsonify(data)


@app.route("/api/gitleaks")
@jwt_required()
def gitleaks():
    data = load_json_file("gitleaks-report.json")
    if data is None:
        return jsonify({"error": "Gitleaks report not found. Run a scan first."}), 404
    return jsonify(data)


@app.route("/api/dast")
@jwt_required()
def dast():
    data = load_json_file("dast-report.json")
    if data is None:
        return jsonify({"error": "DAST report not found. Run a scan first."}), 404
    return jsonify(data)


@app.route("/api/summary")
@jwt_required()
def summary():
    """Aggregate summary across all scanners."""
    sast_data = load_json_file("sast-report.json")
    bandit_data = load_json_file("bandit-report.json")
    trivy_data = load_json_file("trivy-report.json")

    # SAST metrics
    sast_metrics = {"total": 0, "critical": 0, "high": 0, "medium": 0, "low": 0, "languages": [], "tools": []}
    if sast_data and "metrics" in sast_data:
        totals = sast_data["metrics"].get("totals", {})
        sast_metrics = {
            "total": totals.get("total_issues", 0),
            "critical": totals.get("critical", 0),
            "high": totals.get("high", 0),
            "medium": totals.get("medium", 0),
            "low": totals.get("low", 0),
            "languages": sast_data.get("languages_detected", []),
            "tools": sast_data.get("tools_used", []),
        }
    elif bandit_data and "metrics" in bandit_data:
        totals = bandit_data["metrics"].get("_totals", {})
        sast_metrics = {
            "total": len(bandit_data.get("results", [])),
            "critical": 0,
            "high": totals.get("SEVERITY.HIGH", 0),
            "medium": totals.get("SEVERITY.MEDIUM", 0),
            "low": totals.get("SEVERITY.LOW", 0),
            "languages": ["python"],
            "tools": ["bandit"],
        }

    bandit_metrics = {
        "total": sast_metrics["total"],
        "high": sast_metrics["high"],
        "medium": sast_metrics["medium"],
        "low": sast_metrics["low"],
    }

    # Trivy metrics
    trivy_metrics = {"total": 0, "critical": 0, "high": 0, "medium": 0, "low": 0}
    if trivy_data and "Results" in trivy_data:
        for result in trivy_data["Results"]:
            for vuln in result.get("Vulnerabilities", []):
                trivy_metrics["total"] += 1
                sev = vuln.get("Severity", "").upper()
                if sev.lower() in trivy_metrics:
                    trivy_metrics[sev.lower()] += 1

    # Gitleaks metrics
    gitleaks_data = load_json_file("gitleaks-report.json")
    gitleaks_metrics = {"total": 0, "critical": 0, "high": 0, "medium": 0, "tool": "none", "tool_available": False}
    if gitleaks_data:
        gitleaks_metrics = {
            "total": gitleaks_data.get("total_secrets", 0),
            "critical": gitleaks_data.get("metrics", {}).get("critical", 0),
            "high": gitleaks_data.get("metrics", {}).get("high", 0),
            "medium": gitleaks_data.get("metrics", {}).get("medium", 0),
            "tool": gitleaks_data.get("tool", "unknown"),
            "tool_available": gitleaks_data.get("tool_available", False),
        }

    # DAST metrics
    dast_data = load_json_file("dast-report.json")
    dast_metrics = {
        "total": 0, "high": 0, "medium": 0, "low": 0, "informational": 0,
        "tool": "none", "tool_available": False, "target_url": "",
    }
    if dast_data:
        dast_metrics = {
            "total": dast_data.get("total_alerts", 0),
            "high": dast_data.get("metrics", {}).get("high", 0),
            "medium": dast_data.get("metrics", {}).get("medium", 0),
            "low": dast_data.get("metrics", {}).get("low", 0),
            "informational": dast_data.get("metrics", {}).get("informational", 0),
            "tool": dast_data.get("tool", "unknown"),
            "tool_available": dast_data.get("tool_available", False),
            "target_url": dast_data.get("target_url", ""),
        }

    return jsonify({
        "generated_at": datetime.now().isoformat(),
        "sast": sast_metrics,
        "bandit": bandit_metrics,
        "trivy": trivy_metrics,
        "gitleaks": gitleaks_metrics,
        "dast": dast_metrics,
        "languages_detected": sast_metrics["languages"],
        "tools_used": sast_metrics["tools"],
        "total_vulnerabilities": sast_metrics["total"] + trivy_metrics["total"] + gitleaks_metrics["total"] + dast_metrics["total"],
        "critical_count": (
            sast_metrics["critical"] + trivy_metrics["critical"]
            + sast_metrics["high"] + trivy_metrics["high"]
            + gitleaks_metrics["critical"] + gitleaks_metrics["high"]
        ),
    })


@app.route("/api/health")
def health():
    return jsonify({
        "status": "healthy",
        "timestamp": datetime.now().isoformat(),
        "reports": {
            "sast": os.path.exists(os.path.join(REPORT_DIR, "sast-report.json")),
            "bandit": os.path.exists(os.path.join(REPORT_DIR, "bandit-report.json")),
            "trivy": os.path.exists(os.path.join(REPORT_DIR, "trivy-report.json")),
            "gitleaks": os.path.exists(os.path.join(REPORT_DIR, "gitleaks-report.json")),
            "dast": os.path.exists(os.path.join(REPORT_DIR, "dast-report.json")),
        },
    })


# ====================================================================
# NOTIFICATION ROUTES
# ====================================================================

@app.route("/api/notifications", methods=["GET"])
@jwt_required()
def get_all_notifications():
    notifications = Notification.query.order_by(Notification.created_at.desc()).all()
    unread_count = sum(1 for n in notifications if not n.read)
    return jsonify({
        "notifications": [n.to_dict() for n in notifications],
        "unreadCount": unread_count,
        "total": len(notifications),
    })


@app.route("/api/notifications/<notification_id>/read", methods=["POST"])
@jwt_required()
def mark_notification_read(notification_id):
    notif = db.session.get(Notification, notification_id)
    if notif:
        notif.read = True
        db.session.commit()
    return jsonify({"success": True})


@app.route("/api/notifications/read-all", methods=["POST"])
@jwt_required()
def mark_all_notifications_read():
    Notification.query.update({"read": True})
    db.session.commit()
    return jsonify({"success": True})


@app.route("/api/notifications/<notification_id>", methods=["DELETE"])
@jwt_required()
def delete_notification(notification_id):
    notif = db.session.get(Notification, notification_id)
    if notif:
        db.session.delete(notif)
        db.session.commit()
    return jsonify({"success": True})


@app.route("/api/notifications/clear", methods=["DELETE"])
@jwt_required()
def clear_all_notifications():
    Notification.query.delete()
    db.session.commit()
    return jsonify({"success": True})


# ====================================================================
# SETUP STATUS
# ====================================================================

@app.route("/api/setup/status", methods=["GET"])
@jwt_required()
def get_setup_status():
    config = Config.get_instance()
    policy = Policy.get_instance()

    repo_configured = bool((config.github_repo_url or "").strip())
    policy_configured = policy.configured
    initial_scan_completed = config.initial_scan_completed

    has_bandit = os.path.exists(os.path.join(REPORT_DIR, "bandit-report.json"))
    has_trivy = os.path.exists(os.path.join(REPORT_DIR, "trivy-report.json"))
    has_decision = os.path.exists(os.path.join(REPORT_DIR, "security_decision.json"))

    setup_completed = repo_configured and policy_configured and initial_scan_completed

    latest_decision = None
    if has_decision:
        latest_decision = load_json_file("security_decision.json")

    return jsonify({
        "setup_completed": setup_completed,
        "repo_configured": repo_configured,
        "policy_configured": policy_configured,
        "initial_scan_completed": initial_scan_completed,
        "has_reports": {"bandit": has_bandit, "trivy": has_trivy, "decision": has_decision},
        "latest_decision": latest_decision,
        "config": {
            "repo_url": config.github_repo_url or "",
            "branch": config.github_branch or "main",
        },
    })


@app.route("/api/setup/complete", methods=["POST"])
@jwt_required()
def complete_setup():
    current_user = get_current_user_info()
    data = request.get_json()

    repo_url = data.get("repo_url", "").strip()
    branch = data.get("branch", "main").strip()
    policy_data = data.get("policy", {})

    if not repo_url:
        return jsonify({"error": "Repository URL is required"}), 400

    is_valid, error_msg = validate_repo_url(repo_url)
    if not is_valid:
        return jsonify({"error": error_msg}), 400

    config = Config.get_instance()
    config.github_repo_url = repo_url
    config.github_branch = branch
    config.repo_configured = True
    config.updated_at = datetime.now()
    config.updated_by = current_user["username"]
    db.session.commit()

    policy = Policy.get_instance()
    if policy_data:
        if "minScore" in policy_data:
            policy.min_score = max(0, min(100, int(policy_data["minScore"])))
        if "blockCritical" in policy_data:
            policy.block_critical = bool(policy_data["blockCritical"])
        if "blockHigh" in policy_data:
            policy.block_high = bool(policy_data["blockHigh"])
        if "maxCriticalVulns" in policy_data:
            policy.max_critical_vulns = max(0, int(policy_data["maxCriticalVulns"]))
        if "maxHighVulns" in policy_data:
            policy.max_high_vulns = max(0, int(policy_data["maxHighVulns"]))
        if "autoBlock" in policy_data:
            policy.auto_block = bool(policy_data["autoBlock"])
    policy.configured = True
    policy.updated_at = datetime.now()
    policy.updated_by = current_user["username"]
    db.session.commit()

    app.logger.info(f"Setup complete – triggering initial scan for {repo_url}")

    try:
        result = run_pipeline(repo_url=repo_url, branch=branch, run_trivy=True)
        config.initial_scan_completed = True
        config.setup_completed = True
        db.session.commit()
        return jsonify({"success": True, "message": "Setup completed successfully", "scan_result": result.to_dict()})
    except Exception as e:
        app.logger.error(f"Initial scan failed: {e}")
        return jsonify({
            "success": False,
            "error": f"Setup completed but initial scan failed: {str(e)}",
            "config_saved": True,
            "policy_saved": True,
        }), 500


@app.route("/api/setup/reset", methods=["POST"])
@jwt_required()
def reset_setup():
    current_user = get_current_user_info()
    if current_user["role"] != "admin":
        return jsonify({"error": "Admin access required"}), 403

    # Reset config
    config = Config.get_instance()
    config.github_repo_url = ""
    config.github_branch = "main"
    config.auto_scan_enabled = True
    config.scan_on_push = True
    config.target_image = ""
    config.target_directory = ""
    config.setup_completed = False
    config.repo_configured = False
    config.policy_configured = False
    config.initial_scan_completed = False
    config.updated_at = datetime.now()
    config.updated_by = current_user["username"]

    # Reset policy
    policy = Policy.get_instance()
    policy.min_score = 70
    policy.block_critical = True
    policy.block_high = False
    policy.max_critical_vulns = 0
    policy.max_high_vulns = 5
    policy.auto_block = True
    policy.configured = False
    policy.updated_at = datetime.now()
    policy.updated_by = current_user["username"]

    db.session.commit()

    # Clear report files
    for report in ["bandit-report.json", "trivy-report.json", "security_decision.json"]:
        path = os.path.join(REPORT_DIR, report)
        if os.path.exists(path):
            os.remove(path)

    return jsonify({"success": True, "message": "Platform reset to initial state"})


# ====================================================================
# PIPELINE ROUTES
# ====================================================================

@app.route("/api/pipelines", methods=["GET"])
@jwt_required()
def get_pipelines():
    limit = request.args.get("limit", 20, type=int)
    pipelines = pipeline_executor.get_pipelines(limit)
    return jsonify({"pipelines": pipelines, "total": len(pipelines)})


@app.route("/api/pipelines/<pipeline_id>", methods=["GET"])
@jwt_required()
def get_pipeline(pipeline_id):
    pipeline = pipeline_executor.get_pipeline(pipeline_id)
    if not pipeline:
        return jsonify({"error": "Pipeline not found"}), 404
    return jsonify(pipeline)


@app.route("/api/pipelines/latest", methods=["GET"])
@jwt_required()
def get_latest_pipeline():
    pipeline = pipeline_executor.get_latest_pipeline()
    if not pipeline:
        return jsonify({"error": "No pipelines found"}), 404
    check_and_notify_pipeline_completion(pipeline)
    return jsonify(pipeline)


# Track already-notified pipelines
_notified_pipelines: set = set()


def check_and_notify_pipeline_completion(pipeline):
    global _notified_pipelines
    if not pipeline:
        return
    pipeline_id = pipeline.get("id")
    status = pipeline.get("status", "").lower()
    if pipeline_id in _notified_pipelines or status not in ("success", "failed"):
        return

    _notified_pipelines.add(pipeline_id)
    if len(_notified_pipelines) > 100:
        _notified_pipelines = set(list(_notified_pipelines)[-50:])

    security_score = pipeline.get("security_score", 0)
    is_deployable = pipeline.get("is_deployable", False)
    vuln_summary = pipeline.get("vulnerability_summary", {})

    if status == "success":
        if is_deployable:
            add_notification(
                "success",
                "Deployment Approved",
                f"Pipeline passed security checks. Score: {security_score}/100",
                {"pipeline_id": pipeline_id, "security_score": security_score},
            )
        else:
            reasons = []
            if security_score < 70:
                reasons.append(f"Score {security_score} below threshold")
            if vuln_summary.get("critical", 0) > 0:
                reasons.append(f"{vuln_summary['critical']} critical vulnerabilities")
            if vuln_summary.get("high", 0) > 5:
                reasons.append(f"{vuln_summary['high']} high severity issues")
            reason_text = "; ".join(reasons) if reasons else "Security requirements not met"
            add_notification(
                "critical",
                "Deployment Blocked",
                f"Pipeline blocked. {reason_text}. Score: {security_score}/100",
                {"pipeline_id": pipeline_id, "security_score": security_score, "reasons": reasons},
            )
    else:
        add_notification(
            "warning",
            "Pipeline Failed",
            "Security scan failed to complete",
            {"pipeline_id": pipeline_id},
        )


@app.route("/api/pipelines/trigger", methods=["POST"])
@jwt_required()
def trigger_pipeline():
    current_user = get_current_user_info()
    full_user = get_full_user_info(current_user["id"])
    config = Config.get_instance()
    policy = Policy.get_instance()
    data = request.get_json() or {}

    repo_url = data.get("repo_url") or config.github_repo_url
    branch = data.get("branch") or config.github_branch or "main"
    target_dir = data.get("target_dir") or config.target_directory
    image_name = data.get("image_name") or config.target_image

    pipeline = pipeline_executor.create_pipeline(
        repo_url=repo_url,
        branch=branch,
        commit_sha=data.get("commit_sha", "manual"),
        commit_message=data.get("commit_message", f"Manual trigger by {current_user['username']}"),
        author=current_user["username"],
    )

    # Enrich with user info and policy snapshot
    for i, p in enumerate(pipeline_executor.pipeline_history):
        if p["id"] == pipeline.id:
            pipeline_executor.pipeline_history[i]["triggered_by"] = full_user or current_user
            pipeline_executor.pipeline_history[i]["policy_snapshot"] = {
                "minScore": policy.min_score,
                "blockCritical": policy.block_critical,
                "blockHigh": policy.block_high,
                "maxCriticalVulns": policy.max_critical_vulns,
                "maxHighVulns": policy.max_high_vulns,
                "autoBlock": policy.auto_block,
                "capturedAt": datetime.now().isoformat(),
            }
            break
    pipeline_executor._save_pipelines()

    add_notification(
        "info",
        "Pipeline Triggered",
        f"Security scan started for branch '{branch}' by {current_user['username']}",
        {"pipeline_id": pipeline.id, "branch": branch},
    )

    run_pipeline_async(
        pipeline_executor,
        pipeline,
        repo_url=repo_url if repo_url else None,
        target_dir=target_dir if target_dir else None,
        image_name=image_name,
    )

    return jsonify({
        "message": "Pipeline triggered successfully",
        "pipeline_id": pipeline.id,
        "status": pipeline.status.value,
    }), 202


# ====================================================================
# CONFIG ROUTES
# ====================================================================

@app.route("/api/config", methods=["GET"])
@jwt_required()
def get_pipeline_config():
    config = Config.get_instance()
    return jsonify(config.to_dict())


@app.route("/api/config", methods=["PUT"])
@jwt_required()
def update_pipeline_config():
    current_user = get_current_user_info()
    if current_user["role"] != "admin":
        return jsonify({"error": "Admin access required"}), 403

    data = request.get_json()
    config = Config.get_instance()

    field_map = {
        "github_repo_url": "github_repo_url",
        "github_branch": "github_branch",
        "auto_scan_enabled": "auto_scan_enabled",
        "scan_on_push": "scan_on_push",
        "target_image": "target_image",
        "target_directory": "target_directory",
    }
    for json_key, attr in field_map.items():
        if json_key in data:
            setattr(config, attr, data[json_key])

    config.updated_at = datetime.now()
    config.updated_by = current_user["username"]
    db.session.commit()

    return jsonify({"message": "Configuration updated successfully", "config": config.to_dict()})


# ====================================================================
# GITHUB WEBHOOK
# ====================================================================

@app.route("/webhook/github", methods=["POST"])
def github_webhook():
    signature = request.headers.get("X-Hub-Signature-256")
    sig_valid = True
    if GITHUB_WEBHOOK_SECRET != "your-webhook-secret":
        sig_valid = verify_github_signature(request.data, signature)
        if not sig_valid:
            # Log the invalid attempt
            log = WebhookLog(event_type="invalid_signature", signature_valid=False, processed=False)
            db.session.add(log)
            db.session.commit()
            return jsonify({"error": "Invalid signature"}), 401

    event = request.headers.get("X-GitHub-Event", "ping")

    # Log webhook
    wh_log = WebhookLog(
        event_type=event,
        signature_valid=sig_valid,
        processed=(event == "push"),
    )
    db.session.add(wh_log)
    db.session.commit()

    if event == "ping":
        return jsonify({"message": "Pong! Webhook configured successfully"})

    if event != "push":
        return jsonify({"message": f"Event '{event}' ignored"}), 200

    config = Config.get_instance()
    if not config.scan_on_push:
        return jsonify({"message": "Auto-scan disabled"}), 200

    payload = request.get_json()
    repo_url = payload.get("repository", {}).get("clone_url", "")
    branch = payload.get("ref", "refs/heads/main").replace("refs/heads/", "")
    commit = payload.get("head_commit", {})
    commit_sha = commit.get("id", "")
    commit_message = commit.get("message", "")
    author = commit.get("author", {}).get("name", "GitHub")

    configured_branch = config.github_branch or "main"
    if branch != configured_branch:
        return jsonify({"message": f"Branch '{branch}' ignored, watching '{configured_branch}'"}), 200

    pipeline = pipeline_executor.create_pipeline(
        repo_url=repo_url,
        branch=branch,
        commit_sha=commit_sha,
        commit_message=commit_message,
        author=author,
    )

    target_dir = config.target_directory
    image_name = config.target_image

    run_pipeline_async(
        pipeline_executor,
        pipeline,
        repo_url=repo_url,
        target_dir=target_dir if target_dir else None,
        image_name=image_name,
    )

    return jsonify({"message": "Pipeline triggered", "pipeline_id": pipeline.id}), 202


# ====================================================================
# EXTERNAL REPO SCAN API
# ====================================================================

_scan_results: Dict[str, dict] = {}


@app.route("/api/scan/trigger", methods=["POST"])
@jwt_required()
def trigger_external_scan():
    current_user = get_current_user_info()
    data = request.get_json()
    if not data:
        return jsonify({"success": False, "error": "Request body is required"}), 400

    repo_url = data.get("repo_url", "").strip()
    branch = data.get("branch", "main").strip()
    run_trivy = data.get("run_trivy", False)
    async_mode = data.get("async", False)

    if not repo_url:
        return jsonify({"success": False, "error": "repo_url is required"}), 400

    is_valid, error_msg = validate_repo_url(repo_url)
    if not is_valid:
        return jsonify({"success": False, "error": error_msg}), 400

    if not branch:
        branch = "main"

    app.logger.info(f"Scan triggered by {current_user['username']} for {repo_url} (branch: {branch})")

    if async_mode:
        def save_result(result: PipelineResult):
            _scan_results[result.pipeline_id] = result.to_dict()

        pipeline_id = run_pipeline_background(
            repo_url=repo_url, branch=branch, run_trivy=run_trivy, callback=save_result
        )
        return jsonify({
            "success": True,
            "message": "Scan triggered successfully",
            "pipeline_id": pipeline_id,
            "status": "running",
            "repo_url": repo_url,
            "branch": branch,
        }), 202
    else:
        try:
            result = run_pipeline(repo_url=repo_url, branch=branch, run_trivy=run_trivy)
            _scan_results[result.pipeline_id] = result.to_dict()
            response_data = result.to_dict()
            response_data["triggered_by"] = current_user["username"]
            return jsonify(response_data), 200 if result.success else 500
        except Exception as e:
            app.logger.error(f"Scan failed: {str(e)}")
            return jsonify({"success": False, "error": f"Scan failed: {str(e)}"}), 500


@app.route("/api/scan/trigger/<pipeline_id>", methods=["GET"])
@jwt_required()
def get_scan_result(pipeline_id):
    if pipeline_id in _scan_results:
        return jsonify({"found": True, "result": _scan_results[pipeline_id]})
    return jsonify({"found": False, "message": f"No result found for pipeline {pipeline_id}. Scan may still be in progress."}), 404


@app.route("/api/scan/validate", methods=["POST"])
@jwt_required()
def validate_scan_input():
    data = request.get_json() or {}
    repo_url = data.get("repo_url", "").strip()
    branch = data.get("branch", "main").strip()
    errors = []
    if not repo_url:
        errors.append("repo_url is required")
    else:
        is_valid, error_msg = validate_repo_url(repo_url)
        if not is_valid:
            errors.append(error_msg)
    if not branch:
        errors.append("branch cannot be empty")
    if errors:
        return jsonify({"valid": False, "errors": errors}), 400
    return jsonify({"valid": True, "repo_url": repo_url, "branch": branch})


# ====================================================================
# ADMIN PANEL
# ====================================================================

@app.route("/api/admin/stats", methods=["GET"])
@jwt_required()
def admin_stats():
    current_user = get_current_user_info()
    if current_user["role"] != "admin":
        return jsonify({"error": "Admin access required"}), 403

    # User stats via ORM
    total_users = User.query.count()
    admin_count = User.query.filter_by(role="admin").count()
    viewer_count = User.query.filter_by(role="viewer").count()
    user_count = User.query.filter_by(role="user").count()
    google_users = User.query.filter_by(auth_provider="google").count()
    local_users = total_users - google_users

    # Pipeline stats (still from executor)
    pipelines = pipeline_executor.get_pipelines(50)
    total_pipelines = len(pipelines)
    successful = sum(1 for p in pipelines if p.get("status") == "success")
    failed = sum(1 for p in pipelines if p.get("status") == "failed")
    running = sum(1 for p in pipelines if p.get("status") == "running")
    scores = [p.get("security_score") for p in pipelines if p.get("security_score") is not None]
    avg_score = round(sum(scores) / len(scores)) if scores else 0
    deployable_count = sum(1 for p in pipelines if p.get("is_deployable"))
    blocked_count = sum(1 for p in pipelines if p.get("is_deployable") is False)

    reports_status = {
        "sast": os.path.exists(os.path.join(REPORT_DIR, "sast-report.json")),
        "bandit": os.path.exists(os.path.join(REPORT_DIR, "bandit-report.json")),
        "trivy": os.path.exists(os.path.join(REPORT_DIR, "trivy-report.json")),
        "gitleaks": os.path.exists(os.path.join(REPORT_DIR, "gitleaks-report.json")),
        "dast": os.path.exists(os.path.join(REPORT_DIR, "dast-report.json")),
        "decision": os.path.exists(os.path.join(REPORT_DIR, "security_decision.json")),
    }

    config = Config.get_instance()
    policy = Policy.get_instance()

    return jsonify({
        "users": {
            "total": total_users,
            "admins": admin_count,
            "users": user_count,
            "viewers": viewer_count,
            "google_auth": google_users,
            "local_auth": local_users,
        },
        "pipelines": {
            "total": total_pipelines,
            "successful": successful,
            "failed": failed,
            "running": running,
            "avg_security_score": avg_score,
            "deployable": deployable_count,
            "blocked": blocked_count,
        },
        "config": {
            "repo_url": config.github_repo_url or "",
            "branch": config.github_branch or "main",
            "auto_scan": config.auto_scan_enabled,
            "scan_on_push": config.scan_on_push,
            "setup_completed": config.setup_completed,
        },
        "policy": policy.to_dict(),
        "reports": reports_status,
    })


@app.route("/api/admin/users", methods=["GET"])
@jwt_required()
def admin_get_users():
    current_user = get_current_user_info()
    if current_user["role"] != "admin":
        return jsonify({"error": "Admin access required"}), 403

    users = User.query.all()
    safe_users = [u.to_dict(safe=True) for u in users]
    return jsonify({"users": safe_users, "total": len(safe_users)})


@app.route("/api/admin/users/<int:user_id>", methods=["PUT"])
@jwt_required()
def admin_update_user(user_id):
    current_user = get_current_user_info()
    if current_user["role"] != "admin":
        return jsonify({"error": "Admin access required"}), 403

    data = request.get_json()
    user = db.session.get(User, user_id)
    if not user:
        return jsonify({"error": "User not found"}), 404

    valid_roles = ["admin", "user", "viewer"]
    field_map = {
        "role": "role",
        "fullName": "full_name",
        "organization": "organization",
        "roleTitle": "role_title",
        "phone": "phone",
    }
    for json_key, attr in field_map.items():
        if json_key in data:
            if json_key == "role" and data[json_key] not in valid_roles:
                return jsonify({"error": f"Invalid role. Must be one of: {', '.join(valid_roles)}"}), 400
            setattr(user, attr, data[json_key])

    db.session.commit()
    return jsonify({
        "message": "User updated successfully",
        "user": {
            "id": user.id,
            "username": user.username,
            "email": user.email,
            "role": user.role,
            "fullName": user.full_name or "",
        },
    })


@app.route("/api/admin/users/<int:user_id>", methods=["DELETE"])
@jwt_required()
def admin_delete_user(user_id):
    current_user = get_current_user_info()
    if current_user["role"] != "admin":
        return jsonify({"error": "Admin access required"}), 403
    if current_user["id"] == user_id:
        return jsonify({"error": "Cannot delete your own account"}), 400

    user = db.session.get(User, user_id)
    if not user:
        return jsonify({"error": "User not found"}), 404

    username = user.username
    db.session.delete(user)
    db.session.commit()
    return jsonify({"message": f"User '{username}' deleted successfully"})


@app.route("/api/admin/users/<int:user_id>/reset-password", methods=["POST"])
@jwt_required()
def admin_reset_password(user_id):
    current_user = get_current_user_info()
    if current_user["role"] != "admin":
        return jsonify({"error": "Admin access required"}), 403

    data = request.get_json()
    new_password = data.get("newPassword", "")
    if not new_password or len(new_password) < 6:
        return jsonify({"error": "Password must be at least 6 characters"}), 400

    user = db.session.get(User, user_id)
    if not user:
        return jsonify({"error": "User not found"}), 404

    user.password_hash = bcrypt.hashpw(new_password.encode("utf-8"), bcrypt.gensalt()).decode("utf-8")
    db.session.commit()
    return jsonify({"message": f"Password reset for '{user.username}'"})


@app.route("/api/admin/pipelines", methods=["GET"])
@jwt_required()
def admin_get_pipelines():
    current_user = get_current_user_info()
    if current_user["role"] != "admin":
        return jsonify({"error": "Admin access required"}), 403

    limit = request.args.get("limit", 50, type=int)
    status_filter = request.args.get("status", None)
    pipelines = pipeline_executor.get_pipelines(limit)

    if status_filter:
        pipelines = [p for p in pipelines if p.get("status") == status_filter]

    enriched = []
    for p in pipelines:
        entry = dict(p)
        failures = []
        stage_logs = []
        for stage_key, stage_data in (p.get("stages") or {}).items():
            if isinstance(stage_data, dict):
                if stage_data.get("status") == "failed":
                    failures.append({"stage": stage_data.get("name", stage_key), "error": stage_data.get("error", "Unknown error")})
                if stage_data.get("logs"):
                    stage_logs.append({"stage": stage_data.get("name", stage_key), "log": stage_data.get("logs", "")[:200]})
        entry["failure_reasons"] = failures
        entry["stage_logs"] = stage_logs
        enriched.append(entry)

    return jsonify({"pipelines": enriched, "total": len(enriched)})


@app.route("/api/admin/vulnerabilities/summary", methods=["GET"])
@jwt_required()
def admin_vuln_summary():
    current_user = get_current_user_info()
    if current_user["role"] != "admin":
        return jsonify({"error": "Admin access required"}), 403

    critical_findings = []

    sast_data = load_json_file("sast-report.json")
    if sast_data and sast_data.get("results"):
        for issue in sast_data["results"]:
            sev = (issue.get("severity") or "").upper()
            if sev in ("CRITICAL", "HIGH"):
                critical_findings.append({
                    "source": "SAST",
                    "tool": issue.get("tool", "unknown"),
                    "severity": sev,
                    "message": (issue.get("message") or "")[:150],
                    "file": issue.get("file", ""),
                    "line": issue.get("line", 0),
                    "language": issue.get("language", ""),
                    "rule_id": issue.get("rule_id", ""),
                })

    trivy_data = load_json_file("trivy-report.json")
    if trivy_data and trivy_data.get("Results"):
        for result in trivy_data["Results"]:
            for vuln in (result.get("Vulnerabilities") or []):
                sev = (vuln.get("Severity") or "").upper()
                if sev in ("CRITICAL", "HIGH"):
                    critical_findings.append({
                        "source": "Trivy",
                        "tool": "trivy",
                        "severity": sev,
                        "message": (vuln.get("Title") or vuln.get("Description", ""))[:150],
                        "file": vuln.get("PkgName", ""),
                        "line": 0,
                        "vulnerability_id": vuln.get("VulnerabilityID", ""),
                        "fixed_version": vuln.get("FixedVersion", ""),
                    })

    gitleaks_data = load_json_file("gitleaks-report.json")
    if gitleaks_data and gitleaks_data.get("results"):
        for secret in gitleaks_data["results"]:
            critical_findings.append({
                "source": "Gitleaks",
                "tool": "gitleaks",
                "severity": secret.get("severity", "HIGH"),
                "message": f"Secret detected: {secret.get('rule_id', 'unknown')}",
                "file": secret.get("file", ""),
                "line": secret.get("line", 0),
            })

    dast_data = load_json_file("dast-report.json")
    if dast_data and dast_data.get("results"):
        for alert in dast_data["results"]:
            risk = (alert.get("risk") or "LOW").upper()
            if risk in ("HIGH", "MEDIUM"):
                critical_findings.append({
                    "source": "DAST",
                    "tool": dast_data.get("tool", "zap"),
                    "severity": risk,
                    "message": (alert.get("name") or alert.get("description", ""))[:150],
                    "url": alert.get("url", ""),
                    "cwe_id": alert.get("cwe_id", ""),
                })

    severity_order = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3}
    critical_findings.sort(key=lambda x: severity_order.get(x.get("severity", "LOW"), 3))

    return jsonify({"findings": critical_findings[:100], "total": len(critical_findings)})


# ====================================================================
# LOCAL SCAN
# ====================================================================

@app.route("/api/scan/local", methods=["POST"])
@jwt_required()
def scan_local():
    current_user = get_current_user_info()
    data = request.get_json() or {}
    target_dir = data.get("directory")
    image_name = data.get("image_name")

    if not target_dir and not image_name:
        return jsonify({"error": "Either directory or image_name is required"}), 400

    pipeline = pipeline_executor.create_pipeline(
        repo_url="",
        branch="local",
        commit_sha="local",
        commit_message=f"Local scan by {current_user['username']}",
        author=current_user["username"],
    )
    run_pipeline_async(pipeline_executor, pipeline, repo_url=None, target_dir=target_dir, image_name=image_name)
    return jsonify({"message": "Local scan triggered", "pipeline_id": pipeline.id}), 202


@app.route("/api/admin/analytics", methods=["GET"])
@jwt_required()
def admin_analytics():
    current_user = get_current_user_info()
    if current_user["role"] != "admin":
        return jsonify({"error": "Admin access required"}), 403

    critical_count = high_count = medium_count = low_count = total_secrets = 0

    sast_path = os.path.join(REPORT_DIR, "sast-report.json")
    if os.path.exists(sast_path):
        try:
            with open(sast_path) as f:
                sast = json.load(f)
            for finding in sast.get("results", sast.get("findings", [])):
                sev = (finding.get("extra", {}).get("severity", "") or finding.get("severity", "")).upper()
                if sev in ("ERROR", "CRITICAL"):
                    critical_count += 1
                elif sev in ("WARNING", "HIGH"):
                    high_count += 1
                elif sev == "MEDIUM":
                    medium_count += 1
                else:
                    low_count += 1
        except Exception:
            pass

    bandit_path = os.path.join(REPORT_DIR, "bandit-report.json")
    if os.path.exists(bandit_path):
        try:
            with open(bandit_path) as f:
                bandit = json.load(f)
            for finding in bandit.get("results", []):
                sev = finding.get("issue_severity", "").upper()
                if sev == "HIGH":
                    high_count += 1
                elif sev == "MEDIUM":
                    medium_count += 1
                else:
                    low_count += 1
        except Exception:
            pass

    trivy_path = os.path.join(REPORT_DIR, "trivy-report.json")
    if os.path.exists(trivy_path):
        try:
            with open(trivy_path) as f:
                trivy = json.load(f)
            for result in trivy.get("Results", []):
                for vuln in result.get("Vulnerabilities", []):
                    sev = vuln.get("Severity", "").upper()
                    if sev == "CRITICAL":
                        critical_count += 1
                    elif sev == "HIGH":
                        high_count += 1
                    elif sev == "MEDIUM":
                        medium_count += 1
                    else:
                        low_count += 1
        except Exception:
            pass

    gitleaks_path = os.path.join(REPORT_DIR, "gitleaks-report.json")
    if os.path.exists(gitleaks_path):
        try:
            with open(gitleaks_path) as f:
                gl = json.load(f)
            if isinstance(gl, list):
                total_secrets = len(gl)
            elif isinstance(gl, dict):
                total_secrets = len(gl.get("findings", gl.get("results", [])))
        except Exception:
            pass

    import shutil

    system_health = {
        "overallStatus": "online",
        "bandit": "online" if shutil.which("bandit") else "offline",
        "semgrep": "online" if shutil.which("semgrep") else "offline",
        "trivy": "online" if shutil.which("trivy") else "offline",
        "zap": "offline",
        "gitleaks": "online" if shutil.which("gitleaks") else "offline",
        "docker": "online" if shutil.which("docker") else "offline",
        "apiLatency": "< 50ms",
        "queuedJobs": 0,
    }
    if system_health["bandit"] == "offline" and system_health["semgrep"] == "offline":
        system_health["overallStatus"] = "degraded"

    return jsonify({
        "criticalCount": critical_count,
        "highCount": high_count,
        "mediumCount": medium_count,
        "lowCount": low_count,
        "totalSecrets": total_secrets,
        "vulnDistribution": [
            {"name": "Critical", "value": critical_count},
            {"name": "High", "value": high_count},
            {"name": "Medium", "value": medium_count},
            {"name": "Low", "value": low_count},
        ],
        "vulnTrend": [],
        "secretTrend": [],
        "deployTrend": [],
        "systemHealth": system_health,
        "criticalTrend": {"value": critical_count, "direction": "up" if critical_count > 0 else "flat", "label": "current"},
        "secretsTrend": {"value": total_secrets, "direction": "up" if total_secrets > 0 else "flat", "label": "current"},
    })


# ====================================================================
# SETTINGS API
# ====================================================================

def _get_or_create_settings(user: User) -> UserSettings:
    """Return (or create) the UserSettings row for the given user."""
    if user.settings:
        return user.settings
    settings = UserSettings(user_id=user.id)
    db.session.add(settings)
    db.session.commit()
    return settings


@app.route("/api/settings/profile", methods=["GET"])
@jwt_required()
def settings_get_profile():
    identity = get_jwt_identity()
    user = User.query.filter_by(id=int(identity)).first()
    if not user:
        return jsonify({"error": "User not found"}), 404

    settings = _get_or_create_settings(user)
    profile = settings.get_section("profile")

    return jsonify({
        "fullName": profile.get("fullName", user.full_name or ""),
        "email": user.email,
        "organization": profile.get("organization", user.organization or ""),
        "defaultRepoUrl": profile.get("defaultRepoUrl", ""),
        "timezone": profile.get("timezone", "UTC"),
        "preferredLanguage": profile.get("preferredLanguage", "en"),
        "avatarUrl": profile.get("avatarUrl", ""),
    })


@app.route("/api/settings/profile", methods=["PUT"])
@jwt_required()
def settings_update_profile():
    identity = get_jwt_identity()
    user = User.query.filter_by(id=int(identity)).first()
    if not user:
        return jsonify({"error": "User not found"}), 404

    data = request.get_json()
    if not data:
        return jsonify({"error": "No data provided"}), 400

    if "fullName" in data:
        user.full_name = data["fullName"]
    if "organization" in data:
        user.organization = data["organization"]

    settings = _get_or_create_settings(user)
    profile_data = {
        "fullName": data.get("fullName", user.full_name or ""),
        "organization": data.get("organization", user.organization or ""),
        "defaultRepoUrl": data.get("defaultRepoUrl", ""),
        "timezone": data.get("timezone", "UTC"),
        "preferredLanguage": data.get("preferredLanguage", "en"),
        "avatarUrl": data.get("avatarUrl", ""),
    }
    settings.set_section("profile", profile_data)
    db.session.commit()

    return jsonify({"message": "Profile updated", **profile_data})


@app.route("/api/settings/notifications", methods=["GET"])
@jwt_required()
def settings_get_notifications():
    identity = get_jwt_identity()
    user = User.query.filter_by(id=int(identity)).first()
    if not user:
        return jsonify({"error": "User not found"}), 404

    settings = _get_or_create_settings(user)
    prefs = settings.get_section("notifications")

    defaults = {
        "email": {
            "pipelineSuccess": True,
            "pipelineFailure": True,
            "criticalVuln": True,
            "secretDetected": True,
            "deploymentBlocked": False,
        },
        "inApp": True,
        "weeklySummary": True,
        "realtimeWebhook": False,
    }
    merged = {**defaults, **prefs}
    if isinstance(prefs.get("email"), dict):
        merged["email"] = {**defaults["email"], **prefs["email"]}
    return jsonify(merged)


@app.route("/api/settings/notifications", methods=["PUT"])
@jwt_required()
def settings_update_notifications():
    identity = get_jwt_identity()
    user = User.query.filter_by(id=int(identity)).first()
    if not user:
        return jsonify({"error": "User not found"}), 404

    data = request.get_json()
    if not data:
        return jsonify({"error": "No data provided"}), 400

    settings = _get_or_create_settings(user)
    settings.set_section("notifications", data)
    db.session.commit()
    return jsonify({"message": "Notification preferences updated"})


@app.route("/api/settings/scan-preferences", methods=["GET"])
@jwt_required()
def settings_get_scan_prefs():
    identity = get_jwt_identity()
    user = User.query.filter_by(id=int(identity)).first()
    if not user:
        return jsonify({"error": "User not found"}), 404

    settings = _get_or_create_settings(user)
    prefs = settings.get_section("scanPreferences")

    defaults = {
        "scanners": {"sast": True, "dast": True, "trivy": True, "gitleaks": True},
        "severityThreshold": "medium",
        "fastScanMode": False,
        "autoScanOnPush": True,
        "customIgnorePatterns": "",
        "excludedPaths": "",
    }
    merged = {**defaults, **prefs}
    if isinstance(prefs.get("scanners"), dict):
        merged["scanners"] = {**defaults["scanners"], **prefs["scanners"]}
    return jsonify(merged)


@app.route("/api/settings/scan-preferences", methods=["PUT"])
@jwt_required()
def settings_update_scan_prefs():
    identity = get_jwt_identity()
    user = User.query.filter_by(id=int(identity)).first()
    if not user:
        return jsonify({"error": "User not found"}), 404

    data = request.get_json()
    if not data:
        return jsonify({"error": "No data provided"}), 400

    settings = _get_or_create_settings(user)
    settings.set_section("scanPreferences", data)
    db.session.commit()
    return jsonify({"message": "Scan preferences updated"})


@app.route("/api/settings/git-integration", methods=["GET"])
@jwt_required()
def settings_get_git_integration():
    config = Config.get_instance()
    return jsonify({
        "provider": "github",
        "webhookUrl": f"{request.host_url}api/webhook/github",
        "webhookSecret": GITHUB_WEBHOOK_SECRET[:8] + "..." if len(GITHUB_WEBHOOK_SECRET) > 8 else GITHUB_WEBHOOK_SECRET,
        "lastWebhookAt": config.last_webhook_at.isoformat() if config.last_webhook_at else None,
        "repoUrl": config.github_repo_url or "",
        "branch": config.github_branch or "main",
    })


@app.route("/api/settings/git-integration", methods=["PUT"])
@jwt_required()
def settings_update_git_integration():
    data = request.get_json()
    if not data:
        return jsonify({"error": "No data provided"}), 400

    config = Config.get_instance()
    if "provider" in data:
        config.git_provider = data["provider"]
    db.session.commit()
    return jsonify({"message": "Git integration updated"})


@app.route("/api/settings/git-integration/regenerate-secret", methods=["POST"])
@jwt_required()
def settings_regenerate_webhook_secret():
    new_secret = _secrets.token_hex(32)
    return jsonify({"message": "Webhook secret regenerated", "secret": new_secret[:8] + "..."})


@app.route("/api/settings/git-integration/test", methods=["POST"])
@jwt_required()
def settings_test_webhook():
    return jsonify({"message": "Webhook test sent", "status": "ok"})


@app.route("/api/settings/appearance", methods=["GET"])
@jwt_required()
def settings_get_appearance():
    identity = get_jwt_identity()
    user = User.query.filter_by(id=int(identity)).first()
    if not user:
        return jsonify({"error": "User not found"}), 404

    settings = _get_or_create_settings(user)
    prefs = settings.get_section("appearance")
    defaults = {
        "theme": "dark",
        "density": "comfortable",
        "chartStyle": "default",
        "animations": True,
        "autoRefreshInterval": 30,
    }
    return jsonify({**defaults, **prefs})


@app.route("/api/settings/appearance", methods=["PUT"])
@jwt_required()
def settings_update_appearance():
    identity = get_jwt_identity()
    user = User.query.filter_by(id=int(identity)).first()
    if not user:
        return jsonify({"error": "User not found"}), 404

    data = request.get_json()
    if not data:
        return jsonify({"error": "No data provided"}), 400

    settings = _get_or_create_settings(user)
    settings.set_section("appearance", data)
    db.session.commit()
    return jsonify({"message": "Appearance preferences updated"})


@app.route("/api/settings/api-tokens", methods=["GET"])
@jwt_required()
def settings_get_api_tokens():
    identity = get_jwt_identity()
    user = User.query.filter_by(id=int(identity)).first()
    if not user:
        return jsonify({"error": "User not found"}), 404

    tokens = ApiToken.query.filter_by(user_id=user.id).order_by(ApiToken.created_at.desc()).all()
    return jsonify([t.to_dict() for t in tokens])


@app.route("/api/settings/api-tokens", methods=["POST"])
@jwt_required()
def settings_create_api_token():
    identity = get_jwt_identity()
    user = User.query.filter_by(id=int(identity)).first()
    if not user:
        return jsonify({"error": "User not found"}), 404

    data = request.get_json() or {}
    name = data.get("name", "Unnamed Token")
    expires_in = data.get("expiresIn", "30d")

    token_value = f"sntl_{_secrets.token_hex(20)}"
    token_id = str(uuid.uuid4())[:8]

    expire_map = {"7d": 7, "30d": 30, "90d": 90, "1y": 365, "never": None}
    days = expire_map.get(expires_in)
    expires_at = (datetime.now() + timedelta(days=days)) if days else None

    token = ApiToken(
        id=token_id,
        user_id=user.id,
        name=name,
        token_hash=hashlib.sha256(token_value.encode()).hexdigest(),
        expires_at=expires_at,
    )
    db.session.add(token)
    db.session.commit()

    return jsonify({
        "token": token_value,
        "id": token_id,
        "name": name,
        "expires": expires_at.isoformat() if expires_at else None,
    })


@app.route("/api/settings/api-tokens/<token_id>", methods=["DELETE"])
@jwt_required()
def settings_revoke_api_token(token_id):
    identity = get_jwt_identity()
    user = User.query.filter_by(id=int(identity)).first()
    if not user:
        return jsonify({"error": "User not found"}), 404

    token = ApiToken.query.filter_by(id=token_id, user_id=user.id).first()
    if token:
        db.session.delete(token)
        db.session.commit()
    return jsonify({"message": "Token revoked"})


@app.route("/api/settings/security/sessions", methods=["GET"])
@jwt_required()
def settings_get_sessions():
    user_agent = request.headers.get("User-Agent", "Unknown")
    client_ip = request.remote_addr or "Unknown"
    return jsonify([
        {"id": 1, "device": user_agent[:40], "ip": client_ip, "lastActive": datetime.now().isoformat(), "current": True},
    ])


@app.route("/api/settings/security/oauth", methods=["GET"])
@jwt_required()
def settings_get_oauth():
    identity = get_jwt_identity()
    user = User.query.filter_by(id=int(identity)).first()
    if not user:
        return jsonify({"error": "User not found"}), 404

    is_google = user.auth_provider == "google"
    return jsonify({
        "google": {
            "connected": is_google,
            "email": user.email if is_google else None,
        },
    })


@app.route("/api/settings/advanced/export", methods=["GET"])
@jwt_required()
def settings_export_data():
    identity = get_jwt_identity()
    user = User.query.filter_by(id=int(identity)).first()
    if not user:
        return jsonify({"error": "User not found"}), 404

    settings = _get_or_create_settings(user)
    history = pipeline_executor.get_pipelines(50)

    export = {
        "exportedAt": datetime.now().isoformat(),
        "user": {
            "username": user.username,
            "email": user.email,
            "role": user.role,
            "createdAt": user.created_at.isoformat() if user.created_at else None,
        },
        "settings": settings.to_dict(),
        "scanHistory": history[:50],
    }
    return jsonify(export)


@app.route("/api/settings/advanced/reset", methods=["POST"])
@jwt_required()
def settings_reset_preferences():
    identity = get_jwt_identity()
    user = User.query.filter_by(id=int(identity)).first()
    if not user:
        return jsonify({"error": "User not found"}), 404

    settings = _get_or_create_settings(user)
    for section in UserSettings._SECTION_MAP:
        settings.set_section(section, {})
    db.session.commit()
    return jsonify({"message": "All preferences reset to defaults"})


@app.route("/api/settings/advanced/debug", methods=["PUT"])
@jwt_required()
def settings_toggle_debug():
    identity = get_jwt_identity()
    user = User.query.filter_by(id=int(identity)).first()
    if not user:
        return jsonify({"error": "User not found"}), 404

    data = request.get_json() or {}
    settings = _get_or_create_settings(user)
    settings.set_section("debug", {"enabled": data.get("enabled", False)})
    db.session.commit()
    return jsonify({"message": "Debug mode updated"})


# ====================================================================
# ENTRY POINT
# ====================================================================

if __name__ == "__main__":
    app.run(debug=False, host="0.0.0.0", port=5000)
