"""user_scoped_pipelines_and_repositories

Revision ID: 5ae9618b1db2
Revises: cb3372a90194
Create Date: 2026-03-17 00:44:42.396042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ae9618b1db2'
down_revision = 'cb3372a90194'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_repositories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('branch', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_repositories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_repositories_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('pipelines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_repo_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('report_dir', sa.String(length=500), nullable=True))
        batch_op.create_index(batch_op.f('ix_pipelines_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'user_repositories', ['user_repo_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('pipelines', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_pipelines_user_id'))
        batch_op.drop_column('report_dir')
        batch_op.drop_column('user_repo_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('user_repositories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_repositories_user_id'))

    op.drop_table('user_repositories')
    # ### end Alembic commands ###
