"""add_block_on_secrets_dast_and_pipeline_model

Revision ID: cb3372a90194
Revises: 38df311d22c8
Create Date: 2026-03-17 00:31:55.376314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb3372a90194'
down_revision = '38df311d22c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_read'), ['read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('pipelines', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=8),
               existing_nullable=False)
        batch_op.alter_column('commit_sha',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=40),
               existing_nullable=True)
        batch_op.alter_column('commit_message',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)

    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('block_on_secrets', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('block_on_dast_high', sa.Boolean(), nullable=True))

    with op.batch_alter_table('scan_results', schema=None) as batch_op:
        batch_op.alter_column('pipeline_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=8),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan_results', schema=None) as batch_op:
        batch_op.alter_column('pipeline_id',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.drop_column('block_on_dast_high')
        batch_op.drop_column('block_on_secrets')

    with op.batch_alter_table('pipelines', schema=None) as batch_op:
        batch_op.alter_column('commit_message',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('commit_sha',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_read'))

    # ### end Alembic commands ###
